modLoader="javafml"
loaderVersion="[0,)"
license="license"

[[mods]]
modId="examplemod"
version="0"
displayName="example"

# Access Transformers
# Optional, if not specified Forge will attempt to find the default META-INF/accesstransformer.cfg and silently continue if not found. May default to an empty list in a future MC.
# If you specify AT path strings in this list, Forge will attempt to load each of them and throw errors for any that aren't found.
# Specifying an empty list when your mod has no ATs is recommended to opt-out of the default for slightly better loading performance.
# This config option is only supported on Forge 1.21.11-61.0.10. So if you use it, you should also add a dependency constraint on that Forge version.
#accessTransformers = [
#  "META-INF/accesstransformer.cfg"
#]

